### ISSUE TITLE
SpotifyApi#createPlaylist does not work properly

### ISSUE THREAD

**Issue by DaFlo1981** [thelinmichael/spotify-web-api-java#126]
msg: Error parsing JSON.
com.wrapper.spotify.exceptions.detailed.BadRequestException: Error parsing JSON.
	....
       at CreatePlaylistExample.createPlaylist_Sync(CreatePlaylistExample.java:26)
	at CreatePlaylistExample.main(Unknown Source)

I am using the example  spotify-web-api-java/examples/data/playlists/CreatePlaylistExample.java 

It was working before the latest update

**Comment by Dargmuesli** [comment]
There's a major design flaw that causes this issue. This is not as quickly fixable as I'd like, because of differences between the API reference (e.g. [this](https://beta.developer.spotify.com/documentation/web-api/reference/library/remove-albums-user/)) and [the capabilities](https://stackoverflow.com/questions/14561049/setentity-in-httpdelete) of one dependency. That means, I have to think of a new implementation / removing implementations of DELETE with a request body.
I know that this is not the exact problem you've reported, but it is closely connected. I'll work on it within the next days.
