### ISSUE TITLE
Example for pagination 

### ISSUE THREAD

**Issue by Shystee** [thelinmichael/spotify-web-api-java#152]
Can someone give me an example how to go through paging results because I'm lost.

**Comment by Dargmuesli** [comment]
Sorry, but this is the issue tracker for problems with the source code of this project. You will much more likely get individual help for your project on StackOverflow (see [Contributing.md#your-questions](https://github.com/thelinmichael/spotify-web-api-java/blob/master/CONTRIBUTING.md#your-questions)).
I recommend to add additional information to your question on StackOverflow, because what you wrote here is way too generic.
