### ISSUE TITLE
Missing "album_group" attribute of AlbumSimplified

### ISSUE THREAD

**Issue by Selbi182** [thelinmichael/spotify-web-api-java#180]
As returned by the "Get an Artist's Albums":
![album_group](https://user-images.githubusercontent.com/8850085/67724518-95566080-f9df-11e9-8992-776a3969fb36.png)

I specifically want to group my results into four separate playlists, depending on the given album type of the artist. For albums, singles, and compilations this works just by looking at the album type itself, but appears_on is context sensitive to the artist. This is defined by the album group for the AlbumSimplified model, but it's missing in the API:
![AlbumSimplified](https://user-images.githubusercontent.com/8850085/67724641-fa11bb00-f9df-11e9-90ad-f8aaabbe59c7.png)

 I'd be super happy if you could fix this!

**Comment by dargmuesli** [comment]
Uhh, Spotify, what are you guys doing. Looks like they've extended the [Album Simplified specification](https://developer.spotify.com/documentation/web-api/reference/object-model/#album-object-simplified) even more than what was fixed in #177 that was merged two days ago, but I see no blog post explaining this... the `restrictions` object is new too.
Well either way, you (or anyone else) can look at [the recent changes](https://github.com/thelinmichael/spotify-web-api-java/pull/177/files#diff-d9cd2740712e293141fd251372e2bfd6) and apply similar changes for `album_group` and `restrictions`. I'll label this #Hacktoberfest. If no one volunteers within the last few days of October, I'll implement the changes myself :)

**Comment by ZhectorSM** [comment]
Hi guys!
I would like to work on this one.

**Comment by dargmuesli** [comment]
Nice, go ahead! 🔥

**Comment by ZhectorSM** [comment]
Thanks,
I just have a question, in the current version the JsonUtil builder of the class AlbumSimplified doesn't have this 2 atributes, I saw before were there #177 (line 370-378)

```java
private final String releaseDate;
private final ReleaseDatePrecision releaseDatePrecision;
```

The question is should they go on it or not?   if yes I will add them.

**Comment by dargmuesli** [comment]
Yes, indeed. They seem to have gotten lost somewhere in relation to #178.

**Comment by dargmuesli** [comment]
v4.2.0 is on its way.

![image](https://user-images.githubusercontent.com/4778485/67994167-32b1ce80-fc44-11e9-86e3-d2ee15614d5d.png)

**Comment by Selbi182** [comment]
Make the potential hotfix v4.2.0.69

**Comment by dargmuesli** [comment]
Search for bugs! 😉
