### ISSUE TITLE
Retrieving code String Value

### ISSUE THREAD

**Issue by raddiego** [thelinmichael/spotify-web-api-java#197]
I am currently attempting to use the code in order to display a user's top artists, however after building my spotifyAPI object and attempting to build my authorizationCodeRequest object, I am receiving the following error: "Error: code must be supplied." In the example laid out AuithorizationCodeExample.java in the examples folder, there is a blank string declared for the code String object, which is how I am running it as well. Is there a different way that I should be running this? If so, how do I retrieve my code string so that I may fill it in and run the actions I would like to perform after receiving my access token?

**Comment by WagnerChristoph** [comment]
In order to retrieve the authorization code, you have to open the URI returned by the `AuthorizationCodeUriRequest`, have the user log in and authorize access and then retrieve the code as a query parameter from the redirected request made to your `redirect_uri`. You can then use the authorization code in your `AuthorizationCodeRequest` to retrieve your access token.  
The Authorization Code Flow is also described in the [Spotify developer documentation](https://developer.spotify.com/documentation/general/guides/authorization-guide/).

**Comment by dargmuesli** [comment]
Thank you for your kind answer @WagnerChristoph! I consider this question solved. If it isn't, feel free to reopen. I've also [added a hint to the readme](https://github.com/thelinmichael/spotify-web-api-java/commit/3f77b40b9bdd0fb7038b70e9bb239eea3c959f6b) now that links to Spotify's documentation.
