### ISSUE TITLE
MalformedJsonException when trying to get an Album

### ISSUE THREAD

**Issue by lucassouto29** [thelinmichael/spotify-web-api-java#199]
Hi!

I cannot get an album using your API due to this exception:
```java
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 22 path $
```

I have this function, which receives a valid `accessToken` and the `id` of the album.

```java
public Album getAlbum(String token, String id) throws ParseException, SpotifyWebApiException, IOException {
    SpotifyApi api = SpotifyApi.builder().setAccessToken(token).build();
    GetAlbumRequest request = api.getAlbum(id).build();
    return request.execute();
}
```

The album id is the same as your example, `5zT1JLIj9E57p3e1rFm9Uq`.

I try to use your [example](https://github.com/thelinmichael/spotify-web-api-java/blob/master/examples/data/albums/GetAlbumExample.java) but the same exception as above.

I use version `5.0.1`.

What can I do? Thanks!

**Comment by dargmuesli** [comment]
Thanks for your report. That's a bug with the new version 5. It uses the most recent Apache http library incorrectly. I'm working on a fix.

**Comment by dargmuesli** [comment]
The issue is that https://github.com/thelinmichael/spotify-web-api-java/blob/352865aa1c2c02ffed72f026dab2ff2726671609/src/main/java/com/wrapper/spotify/SpotifyHttpManager.java#L257-L259 returns gibberish. And I have no instant idea why. [It's using httpclient5 now](https://github.com/thelinmichael/spotify-web-api-java/commit/0e6db62c845f4ab3489390f8afc223e6b76618cb#diff-13aaef4056d368b9346a76634f468134) but everything is basically kept as it was. Hmm... @WagnerChristoph maybe you have an idea? I'll try further.

**Comment by dargmuesli** [comment]
Got it. Somehow turning off automatic content decompression solves this issue 😄 no idea why.

**Comment by dargmuesli** [comment]
Version 5.0.2 is released and should appear on the mvn repository in a few hours :)

**Comment by lucassouto29** [comment]
Thanks for your quick fix! :rocket:
