### ISSUE TITLE
New endpoints - Podcast API

### ISSUE THREAD

**Issue by Domin0x** [thelinmichael/spotify-web-api-java#201]
Hi, 
On March 20th, Spotify added Podcast related endpoints. More info here: https://developer.spotify.com/community/news/2020/03/20/introducing-podcasts-api/

I wanted to ask if you plan on adding support for these new features?

**Comment by WagnerChristoph** [comment]
Hi,
I'm already working on it, should be completed in 1-2 days.

**Comment by dargmuesli** [comment]
Version `6.0.0-RC1` was just released :)

**Comment by Selbi182** [comment]
Sorry to jump in again, but I'm confused about something here. The new interface IPlaylistItem only returns the model type, nothing else. For an endpoint like getPlaylistsItems(id), which returns an array of PlaylistTracks, how would I fetch information about this individual tracks such id, name, artists?

Previously, this was as simple as playlistTrack.getTrack(), as it returned a fully-featured Track object. This is no longer as straight forward.

I know casting to Track is an option, but that's pretty ugly. Wouldn't it be more sensible to put the shared attributes such as id, name, release date into the interface?

However, personally speaking here, I feel like the two shouldn't be mixed at all. A playlist track item and a playlist podcast item feel like two totally different things (you can't even add the latter to custom playlists for a start). Do they really require a shared interace just because they both happen to resemble some sort of "playlist item"?

**Comment by dargmuesli** [comment]
Hmm, difficult question. This repo's owner once said that this wrapper is intended to be as close to the API spec as possible and it stayed that way. Looking at [object-model/#playlist-track-object](https://developer.spotify.com/documentation/web-api/reference/object-model/#playlist-track-object) the returned "track" is now "a track object or a episode object". That's how Spotify decided to implement their API and that can certainly be called into question.

On the other hand, the actual response object is dependent on the `additional_types` parameter, so we *could* add helper methods. But doing so would add the need for a plethora of other classes, as far as I think, so I'd rather not like to choose this option. We could, of course, move the typecast into this library's helper methods, but that would just move the issue, wouldn't it?

So my choice is to keep the return types as Spotify's API defines it, but I'm open for other arguments :)

**Comment by Selbi182** [comment]
Maybe I'm a little old-fashioned here, but I feel like this is a case where "sticking to the specification" is hurting usability at no added benefit. Arguably, Spotify themselves designing the specification like that seems weird to me in the first place.

Perhaps there is a compromise though. I fully understand why you would want to keep the wrapper as close to the API as possible. However, what speaks against adding some utility/common implementation methods? This doesn't just include playlist tracks; I feel like there are a lot of features that every user of this API is bound to reinvent the wheel for every single time. One example coming to mind immediately would be handling of 429 retry-after timeouts.

This is a philosophical debate on a much larger scale, but maybe you can think about it a little to decide whether you would like to develop into such a direction in the future.

In the case of getPlaylistItems, injecting the expected type seems like a fair solution. Something like getPlaylistItems(id, Track.class) or if you do go the route of common implementations perhaps even getPlaylistTracks(id) and getPlaylistEpisodes(id). Just some brain food to think about.

**Comment by dargmuesli** [comment]
I'm open for PRs that implement such helpers in a package that is separated from the API spec related code :)
