### ISSUE TITLE
getPlaylistsForUser return empty when there are playlists

### ISSUE THREAD

**Issue by imanzano** [thelinmichael/spotify-web-api-java#47]
Im calling the getPlaylistsForUser as following

```
final Api authApi = Api.builder()
                .clientId(System.getProperty("spotify.clientId"))
                .clientSecret(System.getProperty("spotify.client"))
                .build();

final ArrayList<String> scopes = new ArrayList<>();
scopes.add("playlist-read-private");
scopes.add("playlist-read-collaborative");

final ClientCredentialsGrantRequest request = authApi.clientCredentialsGrant().scopes(scopes).build();
final ClientCredentials clientCredentials = request.get();

authApi.setAccessToken(clientCredentials.getAccessToken());

final List<SimplePlaylist> all = new ArrayList<>();

final String user = "an user id";

Page<SimplePlaylist> simplePlaylistPage = authApi.getPlaylistsForUser(user).limit(50).build().get();
List<SimplePlaylist> items = simplePlaylistPage.getItems();

// The items list is empty, even when the user has playlist. 
// I tested wusing curl and the spotify interactive console and I got results.
```

It is a bug or Im doing something wrong ?

**Comment by thelinmichael** [comment]
Hi @imanzano! It's been a while but answering in case you're still working on this or if someone else finds the post. Apologies for the late reply, this project has been on the backburner for a long time and I'm trying to get up to speed again.

Firstly, it doesn't actually matter if you add the `playlist-read-private` or `playlist-read-collaborative` scopes to the authApi. This is because it would require the `user` to approve your application to access their private and collaborative playlists, and that cannot be done using the [Client Credentials flow](https://developer.spotify.com/web-api/authorization-guide/#client-credentials-flow).

With that out of the way, I'd be curious to know if the user has playlists that aren't private or collaborative. If there are no public playlists, the response should in fact be empty.

**Comment by Dargmuesli** [comment]
Scopes for the client credentials flow were removed in b48db358facee63d86904479f8b4c88327ce6637.

**Comment by Dargmuesli** [comment]
Version 2.0.0-RC1 was just released.
