### ISSUE TITLE
Error 404 when users have special charachters in their user ID

### ISSUE THREAD

**Issue by gonzarugil** [thelinmichael/spotify-web-api-java#53]
When i try to use : final PlaylistRequest infoPlayListRequest = api.getPlaylist(user, idP).build();

With an username like #mimble! it throws 404
I believe its because of the use of special charcters in the username

**Comment by JMPerez** [comment]
Hi @gonzarugil! Are you sure `#mimble!` is an existing user id? I'm trying to get information for that user using the Web API and can't find it (see https://developer.spotify.com/web-api/console/get-users-profile/?user_id=%23mimble%21).

What is the playlist id you are trying to load?

**Comment by gonzarugil** [comment]
the playlist is this one: https://open.spotify.com/user/%23mimble%21/playlist/6bEkcjYQT8LOevifZy2QN1

**Comment by JMPerez** [comment]
Buenísima playlist, creo que me la voy a guardar :)

Ahora le echo un ojo y te cuento a ver qué pasa.

**Comment by JMPerez** [comment]
The user_id needs to be URI-encoded when composing the path. The `#` character starts a fragment identifier, so if not escaped it makes the request fail. I think this should be the wrapper's job, not the consumer of the wrapper. I can see the same problem happening in the Javascript wrappers, so this is something that should be fixed in those projects too.

This is definitely a bug in our side. As a workaround you can URI-encode the userid, but it might be a problem if we update the wrapper and it ends up being double encoded.

Interestingly, there seems to be a bug in the Console. Executing the curl command shown in https://developer.spotify.com/web-api/console/get-users-profile/?user_id=%23mimble%21 does work, but the hashtag seems to break the response shown on that page.

**Comment by gonzarugil** [comment]
I already thought of the URI Encoding but it keeps failing, i try with all the possible combinations of 
`String user = URLEncoder.encode(getUser(url), `"UTF-8");`
`String user = URLEncoder.encode(URLDecoder.decode(getUser(url), "UTF-8"), "UTF-8");`
But Spotify keeps sending 404

**Comment by JMPerez** [comment]
Does any of those encoded strings match `%23mimble%21` ?

**Comment by gonzarugil** [comment]
I have tried Hard-Coding the username to insert all the posible combinations of the encoded and non-encoded username (%23mimble%21 , %23mimble! , #mimble%21  and #mimble! ) with no luck.
I have even tried double enconding (sending %2523mimble%2521)

**Comment by eanakhl** [comment]
Hi,

I hope it's fixed in the latest commit. Could you give it a try?

Thanks,
Anastasia

**Comment by Dargmuesli** [comment]
Implemented URLEncoder for path parameters in v2 in commit 9f5ca80f90afca13e02558f081de32673bc94f53.

**Comment by Dargmuesli** [comment]
Version 2.0.0-RC1 was just released.
