### ISSUE TITLE
Follow a user/artist/playlist is not implemented

### ISSUE THREAD

**Issue by coreygarvey** [thelinmichael/spotify-web-api-java#55]
It would be nice to be able to follow users/artists/playlists. 

https://developer.spotify.com/web-api/console/put-playlist-followers/

Is there a work around that will allow me to do this while continuing to use the spotify-web-api-java?

**Comment by thelinmichael** [comment]
Hey @coreygarvey! While this isn't added to this library, you could absolutely make the request yourself since it's basically a HTTP request to Spotify's Web API using an access token of your choice. Read more about the request that this Java client is making [here](https://developer.spotify.com/web-api/follow-playlist/).

**Comment by Dargmuesli** [comment]
I'll implement this in v2. Stay tuned!

**Comment by Dargmuesli** [comment]
I'll close this. Please follow #102 for updates.

**Comment by Dargmuesli** [comment]
Version 2.0.0-RC1 was just released.
